apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-prodcution-e2e-app
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-app
    spec:
      containers:
      - name: complete-prodcution-e2e-app
        image: minhnhan548:latest
        resources:
          requests:
            memory: "128Mi"   # Giảm yêu cầu bộ nhớ
            cpu: "250m"       # Giảm yêu cầu CPU
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080