apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline-service
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose
      targetPort: 8080 # The port on the container to forward traffic to
  type: ClusterIP  # Change to NodePort or LoadBalancer if you want external access